(defpackage :testing-utilities
  (:use :cl :utils)
  (:export :ppstr))

(in-package :testing-utilities)

;;; Turn the output generated by expr (using fmt and indent)
;;; into a string

(defmacro ppstr (expr &key (indent-level 0) (indent-amount 4))
  (let ((s (gensym)))
    `(with-output-to-string (,s)
       (let ((*indent-level* ,indent-level)
	     (*indent-amount* ,indent-amount)
	     (*fmt-ostream* ,s))
	 ,expr))))
